### ISSUE TITLE
Getting Error in PHP 5.4

### ISSUE THREAD

**Issue by GaneshKandu** [Menaprocms/menapro#2]
Hi,

i have installed **Menapro 1.1.7** on **php 5.4** and Getting error 
![screenshot-webuzo web-2018-05-15-13-12-32](https://user-images.githubusercontent.com/12833130/40043648-a9499d46-5814-11e8-918f-a339a7f0e803.png)

in install/controllers/InstallController.php file
line 523
```php
$created_at=date('Y-m-d H:i');
```
line 542
```php
            $query="INSERT INTO ".$prefix."user (username , email, password_hash,lang ,created_at, updated_at,status )VALUES ('".$username."','".$email."','".$password_hash."','".$lang_id."','".$created_at."','".$created_at."','".$status."')";
```
```$created_at``` varibale contain date ```2018-05-15 1:25``` which is to be stored in ```created_at```, ```updated_at``` column

both columns ```created_at```, ```updated_at``` are int(11) type and you trying to store value date type

**Comment by Eseperio** [comment]
PHP 5.5 and greater is supported. Although 7.1 is highly recommended.

**Comment by GaneshKandu** [comment]
is project live ?

**Comment by Eseperio** [comment]
Yes

**Comment by GaneshKandu** [comment]
Hi,

i am getting this Error sometimes while refresh, there is nothing in  error_log file

Error (#32)
An internal server error occurred.
The above error occurred while the Web server was processing your request.
Please contact us if you think this is a server error. Thank you.

![screenshot-webuzo web-2018-05-18-17-55-16](https://user-images.githubusercontent.com/12833130/40234504-a47ecb5e-5a96-11e8-8a1e-c0c44f8c39ee.png)

i think tokenizer,sqlite3,pdo_sqlite,PDO,iconv,ctype extensions are causing this issue when i am disabled this it works fine
on php 5.5, 7.0, 7.1

thanks working !
