### ISSUE TITLE
Using Menapro on Nginx

### ISSUE THREAD

**Issue by paulocoghi** [Menaprocms/menapro#4]
I'm able to translate the .htaccess code generated by Menapro and write it to Nginx.

But I would like to know if Menapro will refuse to work if it doesn't identify Apache as its webserver, or if I can use it on Nginx and manually make the configuration, transleting the rules Menapro inform on its .htaccess to Nginx config file.

**Comment by menapro** [comment]
Will not refuse if apache is not detected. But there is a component to add a security level that depends on apache, and this will not work.
