### ISSUE TITLE
How to get thumbnails in gallery?

### ISSUE THREAD

**Issue by peterb776** [Menaprocms/menapro#5]
I have created a gallery and uploaded 4 images, but in the gallery view only a default image appears. If I click on any of the 4 default images then the real image does show in the lightbox.

This may be because I don't understand how to create thumbnails, but is there any documentation on how to do this?

Thanks,
Peter

![menaprogallery](https://user-images.githubusercontent.com/10865376/43992132-e699af04-9d71-11e8-8687-00916a0c8626.jpg)
![menaprogalleryimage](https://user-images.githubusercontent.com/10865376/43992134-ea5be1fc-9d71-11e8-8d61-ed2809c154d5.jpg)

**Comment by menapro** [comment]
Thumbnails are created automatically. 
It may be the permissions on your installation. If you check https://menaprodemo.com/ you´ll see working.
