### ISSUE TITLE
Nested layout?

### ISSUE THREAD

**Issue by peterb776** [Menaprocms/menapro#6]
Is it possible to have a block arrangement as shown in the attached sketch (tall left-hand column with stacked blocks in the right-hand column)?

Thanks,
Peter
![layout](https://user-images.githubusercontent.com/10865376/44002354-20853ca2-9e39-11e8-81dd-5e4e34ed6cd8.jpg)

**Comment by menapro** [comment]
You can use Split to achieve this. Click the button on the top right cornet to get this. Theme must be ready.
![image](https://user-images.githubusercontent.com/24988871/44016874-d0f763a6-9ed6-11e8-8089-f317ed5a897a.png)
